baseURL = "https://df-sec.github.io/"
languageCode = "en-us"
title = "df_sec"
theme = "m10c"

[params]
  author = "df_sec"
  description = "All about IT Security."
  avatar = "https://avatars.githubusercontent.com/u/64652594?v=4"

[[params.social]]
  icon = "github"
  name = "My GitHub"
  url = "https://github.com/df-sec"
[[params.social]]
  icon = "twitter"
  name = "My Twitter Handle"
  url = "https://twitter.com/df_sec"

[params.style]
    darkColor = "#353b43"
    lightestColor = "#d3d3d3"
    primaryColor = "#66b2ff"
